name: Publish package to NPM

on:
  release:
    types:
      - published

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      # Checkout to target branch
      - uses: actions/checkout@v4
        with:
          # Pull submodules
          submodules: 'recursive'

      - name: Get package info
        id: package
        uses: codex-team/action-nodejs-package-info@v1

      # Setup node environment
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org/

      # Prepare, build and publish project
      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Lint
        run: yarn lint

      - name: Test
        run: yarn test

      # We don't need an explicit build step because prepublishOnly script in package.json will run it
      - name: Publish the package with a NEXT tag
        run: npm publish --access public --tag next --provenance
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Add LATEST tag for the published package if this is not a prerelease version
        if: github.event.release.prerelease != true
        run: npm dist-tag add ${{ steps.package.outputs.name }}@${{ steps.package.outputs.version }} latest
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
